workflowVersion: 1.0.0
sources:
    clerk-java-sdk:
        inputs:
            - location: ../../../../openapi.yml
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-java-sdk
targets:
    my-first-target:
        target: java
        source: clerk-java-sdk
