workflowVersion: 1.0.0
speakeasyVersion: v1.385.0
sources:
    clerk-java-sdk:
        inputs:
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/bapi/2021-02-05.yml
        overlays:
            - location: fixes.yml
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-java-sdk
targets:
    clerk-java:
        target: java
        source: clerk-java-sdk
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $gpg_secret_key
                gpgPassPhrase: $gpg_pass_phrase
